1: Import Libraries and Create Dataset

In [1]:

# Day 21: Date Parsing and Datetime Basics
# Import required libraries

import pandas as pd
import numpy as np

# Create a sample Superstore-style sales dataset

data = {
    "Order_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Customer": ["Aman", "Priya", "Rahul", "Sneha", "Neha",
                 "Ravi", "Anjali", "Karan", "Pooja", "Arjun"],
    "Order_Date": ["2025-01-15", "2025-02-20", "2025-03-10",
                   "2025-04-05", "2025-05-12", "2025-06-18",
                   "2025-07-22", "2025-08-25", "invalid", "2025-10-10"],
    "Sales": [2500, 4000, 1500, 3200, 1800, 2750, 2100, 3500, 2800, 4200]
}

df = pd.DataFrame(data)

print("Original Dataset:")
display(df)

Original Dataset:

   Order_ID Customer  Order_Date  Sales
0       101     Aman  2025-01-15   2500
1       102    Priya  2025-02-20   4000
2       103    Rahul  2025-03-10   1500
3       104    Sneha  2025-04-05   3200
4       105     Neha  2025-05-12   1800
5       106     Ravi  2025-06-18   2750
6       107   Anjali  2025-07-22   2100
7       108    Karan  2025-08-25   3500
8       109    Pooja     invalid   2800
9       110    Arjun  2025-10-10   4200

2: Inspect Dataset and Date Column

In [2]:

# Check dataset information and column data types

print("Dataset Information:")
df.info()

print("\nDate Column:")
display(df["Order_Date"])

print("\nOriginal Data Type:")
print(df["Order_Date"].dtype)

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    10 non-null     int64
 1   Customer    10 non-null     object
 2   Order_Date  10 non-null     object
 3   Sales       10 non-null     int64
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes

Date Column:

0    2025-01-15
1    2025-02-20
2    2025-03-10
3    2025-04-05
4    2025-05-12
5    2025-06-18
6    2025-07-22
7    2025-08-25
8       invalid
9    2025-10-10
Name: Order_Date, dtype: object

Original Data Type:
object

3: Convert String Dates into Datetime

In [3]:

# Convert text dates into Pandas datetime format.
# Invalid date values will become NaT.

df["Order_Date"] = pd.to_datetime(
    df["Order_Date"], errors="coerce"
)

print("After Date Conversion:")
display(df)

print("\nUpdated Data Type:")
print(df["Order_Date"].dtype)

After Date Conversion:

   Order_ID Customer Order_Date  Sales
0       101     Aman 2025-01-15   2500
1       102    Priya 2025-02-20   4000
2       103    Rahul 2025-03-10   1500
3       104    Sneha 2025-04-05   3200
4       105     Neha 2025-05-12   1800
5       106     Ravi 2025-06-18   2750
6       107   Anjali 2025-07-22   2100
7       108    Karan 2025-08-25   3500
8       109    Pooja        NaT   2800
9       110    Arjun 2025-10-10   4200

Updated Data Type:
datetime64[ns]

4: Identify and Handle Invalid Dates

In [4]:

# Identify invalid or missing date values using isna()

invalid_dates = df[df["Order_Date"].isna()]

print("Invalid Date Records:")
display(invalid_dates)

print("Total Invalid Dates:", df["Order_Date"].isna().sum())

# Remove rows having invalid dates

df = df.dropna(subset=["Order_Date"]).copy()

print("\nDataset After Removing Invalid Dates:")
display(df)

Invalid Date Records:

   Order_ID Customer Order_Date  Sales
8       109    Pooja        NaT   2800

Total Invalid Dates: 1

Dataset After Removing Invalid Dates:

   Order_ID Customer Order_Date  Sales
0       101     Aman 2025-01-15   2500
1       102    Priya 2025-02-20   4000
2       103    Rahul 2025-03-10   1500
3       104    Sneha 2025-04-05   3200
4       105     Neha 2025-05-12   1800
5       106     Ravi 2025-06-18   2750
6       107   Anjali 2025-07-22   2100
7       108    Karan 2025-08-25   3500
9       110    Arjun 2025-10-10   4200

5: Extract Year, Month and Day

In [5]:

# Use the .dt accessor to extract date components

df["Year"] = df["Order_Date"].dt.year
df["Month"] = df["Order_Date"].dt.month
df["Day"] = df["Order_Date"].dt.day

print("Dataset with Year, Month and Day:")
display(df)

Dataset with Year, Month and Day:

   Order_ID Customer Order_Date  Sales  Year  Month  Day
0       101     Aman 2025-01-15   2500  2025      1   15
1       102    Priya 2025-02-20   4000  2025      2   20
2       103    Rahul 2025-03-10   1500  2025      3   10
3       104    Sneha 2025-04-05   3200  2025      4    5
4       105     Neha 2025-05-12   1800  2025      5   12
5       106     Ravi 2025-06-18   2750  2025      6   18
6       107   Anjali 2025-07-22   2100  2025      7   22
7       108    Karan 2025-08-25   3500  2025      8   25
9       110    Arjun 2025-10-10   4200  2025     10   10

6: Extract Weekday Information

In [6]:

# Extract weekday name and weekday number

df["Weekday"] = df["Order_Date"].dt.day_name()
df["Weekday_Number"] = df["Order_Date"].dt.dayofweek

print("Dataset with Weekday Information:")
display(df[["Order_ID", "Order_Date", "Weekday", "Weekday_Number"]])

Dataset with Weekday Information:

   Order_ID Order_Date    Weekday  Weekday_Number
0       101 2025-01-15  Wednesday               2
1       102 2025-02-20   Thursday               3
2       103 2025-03-10     Monday               0
3       104 2025-04-05   Saturday               5
4       105 2025-05-12     Monday               0
5       106 2025-06-18  Wednesday               2
6       107 2025-07-22    Tuesday               1
7       108 2025-08-25     Monday               0
9       110 2025-10-10     Friday               4

7: Date Conversion Examples

In [7]:

# Convert dates written in different formats

date_values = pd.Series([
    "15-01-2025",
    "20/02/2025",
    "2025-03-10",
    "invalid_date"
])

converted_dates = pd.to_datetime(
    date_values, format="mixed",
    dayfirst=True, errors="coerce"
)

print("Original Dates:")
display(date_values)

print("Converted Datetime Values:")
display(converted_dates)

Original Dates:

0      15-01-2025
1      20/02/2025
2      2025-03-10
3    invalid_date
dtype: object

Converted Datetime Values:

0   2025-01-15
1   2025-02-20
2   2025-03-10
3          NaT
dtype: datetime64[ns]

8: Filter Records Based on Dates

In [8]:

# Select orders placed in the first quarter

quarter_one = df[df["Order_Date"].dt.quarter == 1]

print("First Quarter Orders:")
display(quarter_one)

# Select orders placed after June 2025

second_half = df[df["Order_Date"] >= "2025-07-01"]

print("\nOrders From July 2025 Onwards:")
display(second_half)

First Quarter Orders:

,Order_ID,Customer,Order_Date,Sales,Year,Month,Day,Weekday,Weekday_Number
0,101,Aman,2025-01-15,2500,2025,1,15,Wednesday,2
1,102,Priya,2025-02-20,4000,2025,2,20,Thursday,3
2,103,Rahul,2025-03-10,1500,2025,3,10,Monday,0

Orders From July 2025 Onwards:

,Order_ID,Customer,Order_Date,Sales,Year,Month,Day,Weekday,Weekday_Number
6,107,Anjali,2025-07-22,2100,2025,7,22,Tuesday,1
7,108,Karan,2025-08-25,3500,2025,8,25,Monday,0
9,110,Arjun,2025-10-10,4200,2025,10,10,Friday,4

l 9: Date-Based Analysis

In [9]:

# Analyze sales based on month and weekday

print("Total Orders:", len(df))
print("Total Sales:", df["Sales"].sum())
print("Average Sales:", round(df["Sales"].mean(), 2))

print("\nMonthly Sales:")
display(df.groupby("Month")["Sales"].sum())

print("\nWeekday-wise Sales:")
display(df.groupby("Weekday")["Sales"].sum())

print("\nYear-wise Orders:")
display(df.groupby("Year")["Order_ID"].count())

Total Orders: 9
Total Sales: 25550
Average Sales: 2838.89

Monthly Sales:

Month
1     2500
2     4000
3     1500
4     3200
5     1800
6     2750
7     2100
8     3500
10    4200
Name: Sales, dtype: int64

Weekday-wise Sales:

Weekday
Friday       4200
Monday       6800
Saturday     3200
Thursday     4000
Tuesday      2100
Wednesday    5250
Name: Sales, dtype: int64

Year-wise Orders:

Year
2025    9
Name: Order_ID, dtype: int64