1 — Import libraries and create dataset

In [1]:

# Day 16: Selecting Rows and Columns with loc[] and iloc[]
# Objective: Practice label-based and position-based DataFrame selection.

import pandas as pd

# Create a sample employee dataset.
df = pd.DataFrame({
    "Name": ["Aarav", "Priya", "Rahul", "Sneha", "Aman", "Neha"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT"],
    "Age": [23, 25, 22, 28, 24, 26],
    "Salary": [35000, 42000, 30000, 50000, 38000, 45000]
}, index=["E101", "E102", "E103", "E104", "E105", "E106"])

print("Employee Dataset:")
display(df)

Employee Dataset:

       Name Department  Age  Salary
E101  Aarav         IT   23   35000
E102  Priya         HR   25   42000
E103  Rahul         IT   22   30000
E104  Sneha    Finance   28   50000
E105   Aman         HR   24   38000
E106   Neha         IT   26   45000

2 — Understanding loc[] (label-based selection)

In [2]:

# loc[] selects rows and columns using their labels.
# Syntax: df.loc[row_label, column_label]

# Example 1: Select a single row by its index label.
print("Example 1: Single row")
display(df.loc["E101"])

# Example 2: Select a single column.
print("Example 2: Name column")
display(df.loc[:, "Name"])

# Example 3: Select specific rows.
print("Example 3: Multiple rows")
display(df.loc[["E101", "E103", "E105"]])

# Example 4: Select specific rows and columns.
print("Example 4: Selected rows and columns")
display(df.loc[["E102", "E104"], ["Name", "Salary"]])

# Example 5: Select rows using a condition.
print("Example 5: Employees with salary above 40000")
display(df.loc[df["Salary"] > 40000, ["Name", "Salary"]])

# Example 6: Select all rows but only two columns.
print("Example 6: Department and Age")
display(df.loc[:, ["Department", "Age"]])

Example 1: Single row

Name          Aarav
Department       IT
Age              23
Salary        35000
Name: E101, dtype: object

Example 2: Name column

E101    Aarav
E102    Priya
E103    Rahul
E104    Sneha
E105     Aman
E106     Neha
Name: Name, dtype: object

Example 3: Multiple rows

       Name Department  Age  Salary
E101  Aarav         IT   23   35000
E103  Rahul         IT   22   30000
E105   Aman         HR   24   38000

Example 4: Selected rows and columns

       Name  Salary
E102  Priya   42000
E104  Sneha   50000

Example 5: Employees with salary above 40000

       Name  Salary
E102  Priya   42000
E104  Sneha   50000
E106   Neha   45000

Example 6: Department and Age

     Department  Age
E101         IT   23
E102         HR   25
E103         IT   22
E104    Finance   28
E105         HR   24
E106         IT   26

3 — Understanding iloc[] (position-based selection)

In [4]:

# iloc[] selects rows and columns using integer positions.
# Positions start from 0.
# Syntax: df.iloc[row_position, column_position]

# Example 1: Select the first row.
print("Example 1: First row")
display(df.iloc[0])

# Example 2: Select the first column.
print("Example 2: First column")
display(df.iloc[:, 0])

# Example 3: Select the first three rows.
print("Example 3: First three rows")
display(df.iloc[0:3])

# Example 4: Select rows and columns by position.
print("Example 4: First three rows and first two columns")
display(df.iloc[0:3, 0:2])

# Example 5: Select a specific row and column.
print("Example 5: Age of the second employee")
display(df.iloc[1, 2])

# Example 6: Select non-consecutive rows and columns.
print("Example 6: Selected positions")
display(df.iloc[[0, 2, 4], [0, 3]])

Example 1: First row

Name          Aarav
Department       IT
Age              23
Salary        35000
Name: E101, dtype: object

Example 2: First column

E101    Aarav
E102    Priya
E103    Rahul
E104    Sneha
E105     Aman
E106     Neha
Name: Name, dtype: object

Example 3: First three rows

       Name Department  Age  Salary
E101  Aarav         IT   23   35000
E102  Priya         HR   25   42000
E103  Rahul         IT   22   30000

Example 4: First three rows and first two columns

       Name Department
E101  Aarav         IT
E102  Priya         HR
E103  Rahul         IT

Example 5: Age of the second employee

np.int64(25)

Example 6: Selected positions

       Name  Salary
E101  Aarav   35000
E103  Rahul   30000
E105   Aman   38000

4 — Comparison of both methods

In [5]:

# loc[] uses labels, while iloc[] uses integer positions.

print("Using loc[]:")
display(df.loc["E102":"E104", ["Name", "Age"]])

print("Using iloc[]:")
display(df.iloc[1:4, [0, 2]])

# Note: loc[] includes the ending label in a label slice.
# iloc[] excludes the ending position in a positional slice.

Using loc[]:

       Name  Age
E102  Priya   25
E103  Rahul   22
E104  Sneha   28

Using iloc[]:

       Name  Age
E102  Priya   25
E103  Rahul   22
E104  Sneha   28

5 — Practical examples

In [6]:

# Practical Example 1: Find IT department employees.
print("IT Department Employees:")
display(df.loc[df["Department"] == "IT", ["Name", "Department", "Salary"]])

# Practical Example 2: Get the last two rows by position.
print("Last two employees:")
display(df.iloc[-2:])

# Practical Example 3: Update a value using loc[].
df.loc["E101", "Salary"] = 36000
print("Updated employee salary:")
display(df.loc["E101"])

# Practical Example 4: Select employees aged 24 or above.
print("Employees aged 24 or above:")
display(df.loc[df["Age"] >= 24, ["Name", "Age"]])

IT Department Employees:

       Name Department  Salary
E101  Aarav         IT   35000
E103  Rahul         IT   30000
E106   Neha         IT   45000

Last two employees:

      Name Department  Age  Salary
E105  Aman         HR   24   38000
E106  Neha         IT   26   45000

Updated employee salary:

Name          Aarav
Department       IT
Age              23
Salary        36000
Name: E101, dtype: object

Employees aged 24 or above:

       Name  Age
E102  Priya   25
E104  Sneha   28
E105   Aman   24
E106   Neha   26

6 — Interview questions and answers

In [7]:

# Q1. What is loc[]?
# Answer: loc[] selects DataFrame data using row and column labels.

# Q2. What is iloc[]?
# Answer: iloc[] selects DataFrame data using integer positions.

# Q3. What is the main difference between loc[] and iloc[]?
# Answer: loc[] is label-based; iloc[] is position-based.

# Q4. Does loc[] include the ending label in a slice?
# Answer: Yes, when using label-based slicing.

# Q5. Does iloc[] include the ending position in a slice?
# Answer: No, the ending position is excluded.

# Q6. How can we select rows using a condition?
# Answer: Use loc[] with a Boolean condition.

print("Interview questions and answers completed.")

Interview questions and answers completed.