1: Import libraries and create dataset

In [1]:

# Day 17: Filtering and Sorting DataFrames
# Objective: Filter records using conditions and sort data in ascending/descending order.

import pandas as pd

# Create a sample employee dataset for practicing filtering and sorting.
df = pd.DataFrame({
    "Name": ["Aarav", "Priya", "Rahul", "Sneha", "Aman",
             "Neha", "Karan", "Pooja", "Riya", "Vikas"],
    "Department": ["IT", "HR", "IT", "Finance", "HR",
                   "IT", "Finance", "IT", "HR", "Finance"],
    "Age": [23, 25, 22, 28, 24, 26, 30, 21, 27, 29],
    "Salary": [35000, 42000, 30000, 50000, 38000,
               45000, 55000, 32000, 40000, 52000],
    "Experience": [1, 3, 1, 5, 2, 4, 7, 1, 4, 6]
})

print("Employee Dataset:")
display(df)

Employee Dataset:

    Name Department  Age  Salary  Experience
0  Aarav         IT   23   35000           1
1  Priya         HR   25   42000           3
2  Rahul         IT   22   30000           1
3  Sneha    Finance   28   50000           5
4   Aman         HR   24   38000           2
5   Neha         IT   26   45000           4
6  Karan    Finance   30   55000           7
7  Pooja         IT   21   32000           1
8   Riya         HR   27   40000           4
9  Vikas    Finance   29   52000           6

2: Filtering examples

In [2]:

# Filtering selects only rows that satisfy a condition.

# Example 1: Employees earning more than 40000.
print("1. Employees with salary above 40000:")
display(df[df["Salary"] > 40000])

# Example 2: Employees working in the IT department.
print("2. IT Department Employees:")
display(df[df["Department"] == "IT"])

# Example 3: Employees aged 25 or above.
print("3. Employees aged 25 or above:")
display(df[df["Age"] >= 25])

# Example 4: Employees with experience of at least 4 years.
print("4. Employees with 4 or more years of experience:")
display(df[df["Experience"] >= 4])

# Example 5: Multiple conditions using & (AND).
print("5. IT employees earning more than 35000:")
display(df[(df["Department"] == "IT") & (df["Salary"] > 35000)])

# Example 6: Multiple conditions using | (OR).
print("6. Employees in HR or Finance:")
display(df[(df["Department"] == "HR") | (df["Department"] == "Finance")])

1. Employees with salary above 40000:

    Name Department  Age  Salary  Experience
1  Priya         HR   25   42000           3
3  Sneha    Finance   28   50000           5
5   Neha         IT   26   45000           4
6  Karan    Finance   30   55000           7
9  Vikas    Finance   29   52000           6

2. IT Department Employees:

    Name Department  Age  Salary  Experience
0  Aarav         IT   23   35000           1
2  Rahul         IT   22   30000           1
5   Neha         IT   26   45000           4
7  Pooja         IT   21   32000           1

3. Employees aged 25 or above:

    Name Department  Age  Salary  Experience
1  Priya         HR   25   42000           3
3  Sneha    Finance   28   50000           5
5   Neha         IT   26   45000           4
6  Karan    Finance   30   55000           7
8   Riya         HR   27   40000           4
9  Vikas    Finance   29   52000           6

4. Employees with 4 or more years of experience:

    Name Department  Age  Salary  Experience
3  Sneha    Finance   28   50000           5
5   Neha         IT   26   45000           4
6  Karan    Finance   30   55000           7
8   Riya         HR   27   40000           4
9  Vikas    Finance   29   52000           6

5. IT employees earning more than 35000:

   Name Department  Age  Salary  Experience
5  Neha         IT   26   45000           4

6. Employees in HR or Finance:

    Name Department  Age  Salary  Experience
1  Priya         HR   25   42000           3
3  Sneha    Finance   28   50000           5
4   Aman         HR   24   38000           2
6  Karan    Finance   30   55000           7
8   Riya         HR   27   40000           4
9  Vikas    Finance   29   52000           6

3: Sorting examples

In [3]:

# sort_values() sorts DataFrame records by column values.
# ascending=True sorts from lowest to highest.
# ascending=False sorts from highest to lowest.

# Example 1: Sort salary in ascending order.
print("1. Salary: Ascending order")
display(df.sort_values(by="Salary", ascending=True))

# Example 2: Sort salary in descending order.
print("2. Salary: Descending order")
display(df.sort_values(by="Salary", ascending=False))

# Example 3: Sort age from youngest to oldest.
print("3. Age: Ascending order")
display(df.sort_values(by="Age"))

# Example 4: Sort experience from highest to lowest.
print("4. Experience: Descending order")
display(df.sort_values(by="Experience", ascending=False))

# Example 5: Sort by department and then salary.
print("5. Department ascending and salary descending:")
display(df.sort_values(by=["Department", "Salary"],
                       ascending=[True, False]))

# Example 6: Sort names alphabetically.
print("6. Names in alphabetical order:")
display(df.sort_values(by="Name"))

1. Salary: Ascending order

    Name Department  Age  Salary  Experience
2  Rahul         IT   22   30000           1
7  Pooja         IT   21   32000           1
0  Aarav         IT   23   35000           1
4   Aman         HR   24   38000           2
8   Riya         HR   27   40000           4
1  Priya         HR   25   42000           3
5   Neha         IT   26   45000           4
3  Sneha    Finance   28   50000           5
9  Vikas    Finance   29   52000           6
6  Karan    Finance   30   55000           7

2. Salary: Descending order

    Name Department  Age  Salary  Experience
6  Karan    Finance   30   55000           7
9  Vikas    Finance   29   52000           6
3  Sneha    Finance   28   50000           5
5   Neha         IT   26   45000           4
1  Priya         HR   25   42000           3
8   Riya         HR   27   40000           4
4   Aman         HR   24   38000           2
0  Aarav         IT   23   35000           1
7  Pooja         IT   21   32000           1
2  Rahul         IT   22   30000           1

3. Age: Ascending order

    Name Department  Age  Salary  Experience
7  Pooja         IT   21   32000           1
2  Rahul         IT   22   30000           1
0  Aarav         IT   23   35000           1
4   Aman         HR   24   38000           2
1  Priya         HR   25   42000           3
5   Neha         IT   26   45000           4
8   Riya         HR   27   40000           4
3  Sneha    Finance   28   50000           5
9  Vikas    Finance   29   52000           6
6  Karan    Finance   30   55000           7

4. Experience: Descending order

    Name Department  Age  Salary  Experience
6  Karan    Finance   30   55000           7
9  Vikas    Finance   29   52000           6
3  Sneha    Finance   28   50000           5
5   Neha         IT   26   45000           4
8   Riya         HR   27   40000           4
1  Priya         HR   25   42000           3
4   Aman         HR   24   38000           2
0  Aarav         IT   23   35000           1
2  Rahul         IT   22   30000           1
7  Pooja         IT   21   32000           1

5. Department ascending and salary descending:

    Name Department  Age  Salary  Experience
6  Karan    Finance   30   55000           7
9  Vikas    Finance   29   52000           6
3  Sneha    Finance   28   50000           5
1  Priya         HR   25   42000           3
8   Riya         HR   27   40000           4
4   Aman         HR   24   38000           2
5   Neha         IT   26   45000           4
0  Aarav         IT   23   35000           1
7  Pooja         IT   21   32000           1
2  Rahul         IT   22   30000           1

6. Names in alphabetical order:

    Name Department  Age  Salary  Experience
0  Aarav         IT   23   35000           1
4   Aman         HR   24   38000           2
6  Karan    Finance   30   55000           7
5   Neha         IT   26   45000           4
7  Pooja         IT   21   32000           1
1  Priya         HR   25   42000           3
2  Rahul         IT   22   30000           1
8   Riya         HR   27   40000           4
3  Sneha    Finance   28   50000           5
9  Vikas    Finance   29   52000           6

4: Analysis of filtered records

In [4]:

# Analyze employees who earn more than 40000.
filtered_df = df[df["Salary"] > 40000]

print("Filtered Employee Records:")
display(filtered_df)

# Count the employees matching the condition.
print("Number of employees earning above 40000:",
      len(filtered_df))

# Calculate the average salary of filtered employees.
print("Average salary of filtered employees:",
      round(filtered_df["Salary"].mean(), 2))

# Find the highest salary among filtered employees.
print("Highest salary in filtered records:",
      filtered_df["Salary"].max())

# Show filtered employees from highest to lowest salary.
print("Filtered employees sorted by salary:")
display(filtered_df.sort_values(by="Salary", ascending=False))

Filtered Employee Records:

    Name Department  Age  Salary  Experience
1  Priya         HR   25   42000           3
3  Sneha    Finance   28   50000           5
5   Neha         IT   26   45000           4
6  Karan    Finance   30   55000           7
9  Vikas    Finance   29   52000           6

Number of employees earning above 40000: 5
Average salary of filtered employees: 48800.0
Highest salary in filtered records: 55000
Filtered employees sorted by salary:

    Name Department  Age  Salary  Experience
6  Karan    Finance   30   55000           7
9  Vikas    Finance   29   52000           6
3  Sneha    Finance   28   50000           5
5   Neha         IT   26   45000           4
1  Priya         HR   25   42000           3

5: Department-wise analysis

In [5]:

# Group employees by department and calculate average salary.
print("Average Salary by Department:")
display(df.groupby("Department")["Salary"].mean().round(2))

# Count employees in each department.
print("Employees per Department:")
display(df["Department"].value_counts())

# Find the employee with the highest salary.
highest_paid = df.loc[df["Salary"].idxmax()]

print("Highest Paid Employee:")
display(highest_paid)

Average Salary by Department:

Department
Finance    52333.33
HR         40000.00
IT         35500.00
Name: Salary, dtype: float64

Employees per Department:

Department
IT         4
HR         3
Finance    3
Name: count, dtype: int64

Highest Paid Employee:

Name            Karan
Department    Finance
Age                30
Salary          55000
Experience          7
Name: 6, dtype: object