1: Import libraries and create dataset

In [1]:

# Day 20: Data Types and Type Conversion
# Objective: Inspect and convert DataFrame columns to appropriate data types.

import pandas as pd

# Create a sample customer dataset with mixed data types.
df = pd.DataFrame({
    "CustomerID": ["101", "102", "103", "104", "105", "106"],
    "Name": ["Aarav", "Priya", "Rahul", "Sneha", "Aman", "Neha"],
    "Age": ["25", "30", "22", "28", "24", "27"],
    "PurchaseAmount": ["2500.50", "4000.00", "1500.75",
                       "3200.25", "1800.00", "2750.50"],
    "IsMember": ["True", "False", "True", "False", "True", "False"],
    "JoinDate": ["2025-01-15", "2025-02-20", "2025-03-10",
                 "2025-04-05", "2025-05-12", "2025-06-18"]
})

print("Original Dataset:")
display(df)

Original Dataset:

  CustomerID   Name Age PurchaseAmount IsMember    JoinDate
0        101  Aarav  25        2500.50     True  2025-01-15
1        102  Priya  30        4000.00    False  2025-02-20
2        103  Rahul  22        1500.75     True  2025-03-10
3        104  Sneha  28        3200.25    False  2025-04-05
4        105   Aman  24        1800.00     True  2025-05-12
5        106   Neha  27        2750.50    False  2025-06-18

2: Inspect data types

In [2]:

# dtypes shows the data type of each column.
print("Data Types of Each Column:")
print(df.dtypes)

# info() provides column names, non-null counts, and data types.
print("\nDataset Information:")
df.info()

# Check the number of rows and columns.
print("\nDataset Shape:", df.shape)

Data Types of Each Column:
CustomerID        object
Name              object
Age               object
PurchaseAmount    object
IsMember          object
JoinDate          object
dtype: object

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      6 non-null      object
 1   Name            6 non-null      object
 2   Age             6 non-null      object
 3   PurchaseAmount  6 non-null      object
 4   IsMember        6 non-null      object
 5   JoinDate        6 non-null      object
dtypes: object(6)
memory usage: 420.0+ bytes

Dataset Shape: (6, 6)

3: Convert columns to numeric types

In [3]:

# astype() converts a column to a specified data type.

# Convert CustomerID and Age from strings to integers.
df["CustomerID"] = df["CustomerID"].astype(int)
df["Age"] = df["Age"].astype(int)

# Convert PurchaseAmount from strings to floating-point numbers.
df["PurchaseAmount"] = pd.to_numeric(df["PurchaseAmount"])

print("After Numeric Conversion:")
display(df)

print("\nUpdated Data Types:")
print(df.dtypes)

After Numeric Conversion:

   CustomerID   Name  Age  PurchaseAmount IsMember    JoinDate
0         101  Aarav   25         2500.50     True  2025-01-15
1         102  Priya   30         4000.00    False  2025-02-20
2         103  Rahul   22         1500.75     True  2025-03-10
3         104  Sneha   28         3200.25    False  2025-04-05
4         105   Aman   24         1800.00     True  2025-05-12
5         106   Neha   27         2750.50    False  2025-06-18

Updated Data Types:
CustomerID          int64
Name               object
Age                 int64
PurchaseAmount    float64
IsMember           object
JoinDate           object
dtype: object

4: Convert strings to booleans and dates

In [4]:

# Convert text values into actual Boolean values.
# Explicit mapping avoids treating non-empty strings like "False" as True.
df["IsMember"] = df["IsMember"].map({
    "True": True,
    "False": False
}).astype(bool)

# Convert JoinDate from string to datetime.
df["JoinDate"] = pd.to_datetime(df["JoinDate"], errors="coerce")

print("After Boolean and Date Conversion:")
display(df)

print("\nUpdated Data Types:")
print(df.dtypes)

After Boolean and Date Conversion:

   CustomerID   Name  Age  PurchaseAmount  IsMember   JoinDate
0         101  Aarav   25         2500.50      True 2025-01-15
1         102  Priya   30         4000.00     False 2025-02-20
2         103  Rahul   22         1500.75      True 2025-03-10
3         104  Sneha   28         3200.25     False 2025-04-05
4         105   Aman   24         1800.00      True 2025-05-12
5         106   Neha   27         2750.50     False 2025-06-18

Updated Data Types:
CustomerID                 int64
Name                      object
Age                        int64
PurchaseAmount           float64
IsMember                    bool
JoinDate          datetime64[ns]
dtype: object

5: Handle invalid values safely

In [5]:

# to_numeric(errors="coerce") converts invalid numeric values to NaN.
sample_values = pd.Series(["100", "250.5", "invalid", "400"])

converted_values = pd.to_numeric(sample_values, errors="coerce")

print("Original Values:")
display(sample_values)

print("Converted Numeric Values:")
display(converted_values)

# Check for missing or invalid values.
print("Missing or Invalid Values:")
print(converted_values.isna().sum())

Original Values:

0        100
1      250.5
2    invalid
3        400
dtype: object

Converted Numeric Values:

0    100.0
1    250.5
2      NaN
3    400.0
dtype: float64

Missing or Invalid Values:
1

6: Final cleaned dataset and validation

In [6]:

# Create a cleaned copy with appropriate data types.
clean_df = df.copy()

print("Final Cleaned Dataset:")
display(clean_df)

print("Final Data Types:")
print(clean_df.dtypes)

# Verify the expected data types.
print("\nValidation Results:")
print("CustomerID is integer:", pd.api.types.is_integer_dtype(clean_df["CustomerID"]))
print("Age is integer:", pd.api.types.is_integer_dtype(clean_df["Age"]))
print("PurchaseAmount is numeric:", pd.api.types.is_numeric_dtype(clean_df["PurchaseAmount"]))
print("IsMember is Boolean:", pd.api.types.is_bool_dtype(clean_df["IsMember"]))
print("JoinDate is datetime:", pd.api.types.is_datetime64_any_dtype(clean_df["JoinDate"]))

Final Cleaned Dataset:

   CustomerID   Name  Age  PurchaseAmount  IsMember   JoinDate
0         101  Aarav   25         2500.50      True 2025-01-15
1         102  Priya   30         4000.00     False 2025-02-20
2         103  Rahul   22         1500.75      True 2025-03-10
3         104  Sneha   28         3200.25     False 2025-04-05
4         105   Aman   24         1800.00      True 2025-05-12
5         106   Neha   27         2750.50     False 2025-06-18

Final Data Types:
CustomerID                 int64
Name                      object
Age                        int64
PurchaseAmount           float64
IsMember                    bool
JoinDate          datetime64[ns]
dtype: object

Validation Results:
CustomerID is integer: True
Age is integer: True
PurchaseAmount is numeric: True
IsMember is Boolean: True
JoinDate is datetime: True