1: Import libraries and create dataset

In [1]:

# Day 19: Duplicate Records and Data Validation
# Objective: Identify duplicates, clean data, and validate records.

import pandas as pd

# Create a sample customer dataset containing duplicates and invalid values.
df = pd.DataFrame({
    "CustomerID": [101, 102, 103, 103, 104, 105, 106, 107, 108, 109],
    "Name": ["Aarav", "Priya", "Rahul", "Rahul", "Sneha",
             "Aman", "Neha", "", "Karan", "Pooja"],
    "Age": [25, 30, 22, 22, 28, -5, 35, 24, 150, 27],
    "City": ["Indore", "Bhopal", "Indore", "Indore", "Dewas",
             "Ujjain", "Bhopal", "Indore", "Dewas", "Bhopal"],
    "PurchaseAmount": [2500, 4000, 1500, 1500, 3200,
                       2000, 5000, 1800, -500, 2800]
})

print("Original Customer Dataset:")
display(df)

Original Customer Dataset:

   CustomerID   Name  Age    City  PurchaseAmount
0         101  Aarav   25  Indore            2500
1         102  Priya   30  Bhopal            4000
2         103  Rahul   22  Indore            1500
3         103  Rahul   22  Indore            1500
4         104  Sneha   28   Dewas            3200
5         105   Aman   -5  Ujjain            2000
6         106   Neha   35  Bhopal            5000
7         107          24  Indore            1800
8         108  Karan  150   Dewas            -500
9         109  Pooja   27  Bhopal            2800

2: Identify duplicate records

In [2]:

# duplicated() identifies duplicate rows.
# keep=False marks every occurrence of a duplicated record as True.

print("Duplicate rows:")
display(df[df.duplicated(keep=False)])

# Count duplicate rows excluding the first occurrence.
print("Number of duplicate rows:",
      df.duplicated().sum())

# Check duplicate CustomerID values.
print("Records with duplicate CustomerID:")
display(df[df.duplicated(subset=["CustomerID"], keep=False)])

Duplicate rows:

   CustomerID   Name  Age    City  PurchaseAmount
2         103  Rahul   22  Indore            1500
3         103  Rahul   22  Indore            1500

Number of duplicate rows: 1
Records with duplicate CustomerID:

   CustomerID   Name  Age    City  PurchaseAmount
2         103  Rahul   22  Indore            1500
3         103  Rahul   22  Indore            1500

3: Remove unwanted duplicates

In [3]:

# drop_duplicates() removes repeated records.
# Keep the first occurrence of each identical row.

clean_df = df.drop_duplicates().copy()

print("Dataset after removing exact duplicate rows:")
display(clean_df)

print("Rows before cleaning:", len(df))
print("Rows after cleaning:", len(clean_df))
print("Rows removed:", len(df) - len(clean_df))

Dataset after removing exact duplicate rows:

   CustomerID   Name  Age    City  PurchaseAmount
0         101  Aarav   25  Indore            2500
1         102  Priya   30  Bhopal            4000
2         103  Rahul   22  Indore            1500
4         104  Sneha   28   Dewas            3200
5         105   Aman   -5  Ujjain            2000
6         106   Neha   35  Bhopal            5000
7         107          24  Indore            1800
8         108  Karan  150   Dewas            -500
9         109  Pooja   27  Bhopal            2800

Rows before cleaning: 10
Rows after cleaning: 9
Rows removed: 1

4: Perform data validation checks

In [4]:

# Validation checks help identify missing, invalid, or inconsistent values.

# Check 1: Missing values in each column.
print("1. Missing values:")
display(clean_df.isnull().sum())

# Check 2: Blank customer names.
print("2. Blank names:")
display(clean_df[clean_df["Name"].str.strip() == ""])

# Check 3: Invalid ages (expected range: 1 to 100).
print("3. Invalid ages:")
display(clean_df[(clean_df["Age"] < 1) | (clean_df["Age"] > 100)])

# Check 4: Invalid purchase amounts (must be non-negative).
print("4. Invalid purchase amounts:")
display(clean_df[clean_df["PurchaseAmount"] < 0])

# Check 5: Customer IDs must be unique.
print("5. Duplicate CustomerIDs:")
display(clean_df[clean_df.duplicated(subset=["CustomerID"], keep=False)])

# Check 6: Check whether ages are numeric.
print("6. Age data type:")
print(clean_df["Age"].dtype)

1. Missing values:

CustomerID        0
Name              0
Age               0
City              0
PurchaseAmount    0
dtype: int64

2. Blank names:

   CustomerID Name  Age    City  PurchaseAmount
7         107        24  Indore            1800

3. Invalid ages:

   CustomerID   Name  Age    City  PurchaseAmount
5         105   Aman   -5  Ujjain            2000
8         108  Karan  150   Dewas            -500

4. Invalid purchase amounts:

   CustomerID   Name  Age   City  PurchaseAmount
8         108  Karan  150  Dewas            -500

5. Duplicate CustomerIDs:

Empty DataFrame
Columns: [CustomerID, Name, Age, City, PurchaseAmount]
Index: []

6. Age data type:
int64

5: Clean invalid records

In [5]:

# Remove records that fail basic validation.
# These rules are examples and should be adapted to real business requirements.

validated_df = clean_df[
    (clean_df["Name"].str.strip() != "") &
    (clean_df["Age"].between(1, 100)) &
    (clean_df["PurchaseAmount"] >= 0)
].copy()

# Remove repeated CustomerIDs, keeping the first valid record.
validated_df = validated_df.drop_duplicates(
    subset=["CustomerID"], keep="first"
)

print("Validated and cleaned dataset:")
display(validated_df)

print("Records before validation:", len(clean_df))
print("Records after validation:", len(validated_df))

Validated and cleaned dataset:

   CustomerID   Name  Age    City  PurchaseAmount
0         101  Aarav   25  Indore            2500
1         102  Priya   30  Bhopal            4000
2         103  Rahul   22  Indore            1500
4         104  Sneha   28   Dewas            3200
6         106   Neha   35  Bhopal            5000
9         109  Pooja   27  Bhopal            2800

Records before validation: 9
Records after validation: 6

6: Compare data before and after cleaning

In [6]:

# Compare the dataset size before and after cleaning.
summary = pd.DataFrame({
    "Stage": ["Original Dataset", "After Duplicate Removal", "After Validation"],
    "Number of Records": [len(df), len(clean_df), len(validated_df)]
})

print("Data Cleaning Summary:")
display(summary)

# Verify that the final dataset has unique CustomerIDs.
print("All CustomerIDs unique:",
      validated_df["CustomerID"].is_unique)

# Verify that no negative purchase amounts remain.
print("No negative purchase amounts:",
      (validated_df["PurchaseAmount"] >= 0).all())

# Verify that all ages are within the accepted range.
print("All ages valid:",
      validated_df["Age"].between(1, 100).all())

Data Cleaning Summary:

                     Stage  Number of Records
0         Original Dataset                 10
1  After Duplicate Removal                  9
2         After Validation                  6

All CustomerIDs unique: True
No negative purchase amounts: True
All ages valid: True